# Generated by Django 4.2.30 on 2026-06-12 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField(max_length=1000, unique=True)),
                ('description', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('article_date', models.DateField()),
            ],
            options={
                'ordering': ['-article_date'],
            },
        ),
    ]
